#remote_theme: pages-themes/hacker@v0.2.0
#theme: minima
remote_theme: jekyll/minima@d4d779a
minima:
  skin: dark

nav_pages:
  - about.md

title: ğŸ“¡ MQTT Antena

author: github.com/buzzlightyear-dev
